# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/axis_tut/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/axis_tut/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib C:/axis_tut/project_1/project_1.srcs/sources_1/new/inverse_color.vhd
synth_design -top inverse_color -part xc7z020clg484-1
write_checkpoint -noxdef inverse_color.dcp
catch { report_utilization -file inverse_color_utilization_synth.rpt -pb inverse_color_utilization_synth.pb }
