# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/axis_tut/ip_repo/inverse_color_new_1.0/tmp_edit_project.cache/wt [current_project]
set_property parent.project_path C:/axis_tut/ip_repo/inverse_color_new_1.0/tmp_edit_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  c:/axis_tut/ip_repo/inverse_color_1.0
  c:/axis_tut/ip_repo/inverse_color_new_1.0
  c:/axis_tut/ip_repo/inverse_color_1.0
  c:/axis_tut/ip_repo/inverse_color_1.0
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib C:/axis_tut/ip_repo/inverse_color_new_1.0/src/inverse_color_v1_0.vhd
synth_design -top inverse_color_v1_0 -part xc7z020clg484-1
write_checkpoint -noxdef inverse_color_v1_0.dcp
catch { report_utilization -file inverse_color_v1_0_utilization_synth.rpt -pb inverse_color_v1_0_utilization_synth.pb }
