# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/axis_tut/tpg/src/constraints/ZYBO_Master.xdc

# Block Designs: bd/hdmi_out/hdmi_out.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out || ORIG_REF_NAME==hdmi_out}]

# IP: bd/hdmi_out/ip/hdmi_out_axi_dynclk_0_0/hdmi_out_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_axi_dynclk_0_0 || ORIG_REF_NAME==hdmi_out_axi_dynclk_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_axi_gpio_hdmi_0/hdmi_out_axi_gpio_hdmi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_axi_gpio_hdmi_0 || ORIG_REF_NAME==hdmi_out_axi_gpio_hdmi_0}]

# IP: bd/hdmi_out/ip/hdmi_out_proc_sys_reset_0_0/hdmi_out_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_proc_sys_reset_0_0 || ORIG_REF_NAME==hdmi_out_proc_sys_reset_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_processing_system7_0_0/hdmi_out_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_processing_system7_0_0 || ORIG_REF_NAME==hdmi_out_processing_system7_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_processing_system7_0_axi_periph_0/hdmi_out_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==hdmi_out_processing_system7_0_axi_periph_0}]

# IP: bd/hdmi_out/ip/hdmi_out_xbar_0/hdmi_out_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_xbar_0 || ORIG_REF_NAME==hdmi_out_xbar_0}]

# IP: bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/hdmi_out_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_rgb2dvi_0_0 || ORIG_REF_NAME==hdmi_out_rgb2dvi_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_out_v_axi4s_vid_out_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_v_tc_0_0/hdmi_out_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_v_tc_0_0 || ORIG_REF_NAME==hdmi_out_v_tc_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_xlconstant_0_0/hdmi_out_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_xlconstant_0_0 || ORIG_REF_NAME==hdmi_out_xlconstant_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_xlconstant_1_0/hdmi_out_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_xlconstant_1_0 || ORIG_REF_NAME==hdmi_out_xlconstant_1_0}]

# IP: bd/hdmi_out/ip/hdmi_out_test_pattern_generator_v1_0_0_0/hdmi_out_test_pattern_generator_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_test_pattern_generator_v1_0_0_0 || ORIG_REF_NAME==hdmi_out_test_pattern_generator_v1_0_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_inverse_color_v1_0_0_1/hdmi_out_inverse_color_v1_0_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_inverse_color_v1_0_0_1 || ORIG_REF_NAME==hdmi_out_inverse_color_v1_0_0_1}]

# IP: bd/hdmi_out/ip/hdmi_out_auto_pc_0/hdmi_out_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_auto_pc_0 || ORIG_REF_NAME==hdmi_out_auto_pc_0}]

# XDC: bd/hdmi_out/ip/hdmi_out_axi_gpio_hdmi_0/hdmi_out_axi_gpio_hdmi_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_axi_gpio_hdmi_0 || ORIG_REF_NAME==hdmi_out_axi_gpio_hdmi_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_axi_gpio_hdmi_0/hdmi_out_axi_gpio_hdmi_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_axi_gpio_hdmi_0/hdmi_out_axi_gpio_hdmi_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_axi_gpio_hdmi_0 || ORIG_REF_NAME==hdmi_out_axi_gpio_hdmi_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_proc_sys_reset_0_0/hdmi_out_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_proc_sys_reset_0_0 || ORIG_REF_NAME==hdmi_out_proc_sys_reset_0_0}]

# XDC: bd/hdmi_out/ip/hdmi_out_proc_sys_reset_0_0/hdmi_out_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_proc_sys_reset_0_0 || ORIG_REF_NAME==hdmi_out_proc_sys_reset_0_0}]

# XDC: bd/hdmi_out/ip/hdmi_out_proc_sys_reset_0_0/hdmi_out_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_processing_system7_0_0/hdmi_out_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_processing_system7_0_0 || ORIG_REF_NAME==hdmi_out_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_out/ip/hdmi_out_xbar_0/hdmi_out_xbar_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/src/rgb2dvi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_rgb2dvi_0_0 || ORIG_REF_NAME==hdmi_out_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_rgb2dvi_0_0 || ORIG_REF_NAME==hdmi_out_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_out_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_v_tc_0_0/hdmi_out_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_v_tc_0_0 || ORIG_REF_NAME==hdmi_out_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_v_tc_0_0/hdmi_out_v_tc_0_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_auto_pc_0/hdmi_out_auto_pc_0_ooc.xdc

# XDC: bd/hdmi_out/hdmi_out_ooc.xdc
